/* Generated by re2c 0.13.6 on Wed Oct 30 11:35:05 2013 */
#include <assert.h>
#include <memory.h>
#include <stdio.h>
#include <string.h>

#include "mjson.h"

enum mjson_token_t
{
    TOK_NONE                =  0,
    TOK_IDENTIFIER          =  1,
    TOK_NOESC_STRING        =  2,
    TOK_STRING              =  3,
    TOK_OCT_NUMBER          =  4,
    TOK_HEX_NUMBER          =  5,
    TOK_DEC_NUMBER          =  6,
    TOK_FLOAT_NUMBER        =  7,
    TOK_COMMA               =  8,
    TOK_COLON               =  9,
    TOK_EQUAL               = 10,
    TOK_LEFT_BRACKET        = 11,
    TOK_RIGHT_BRACKET       = 12,
    TOK_LEFT_CURVE_BRACKET  = 13,
    TOK_RIGHT_CURVE_BRACKET = 14,
    TOK_FALSE               = 15,
    TOK_TRUE                = 16,
    TOK_NULL                = 17,
    TOK_WHITESPACE          = 18,
    TOK_INVALID             = 19
};

struct _mjson_parser_t
{
    int token;
    const char* start;
    const char* next;
    const char* end;
    uint8_t* bjson;
    uint8_t* bjson_limit;
};

#ifdef _MSC_VER
#   pragma pack(push, 1)
#else
#   error "proper packing not implemented!!!"
#endif

struct _mjson_entry_t
{
    uint32_t  id;
    union
    {
        uint32_t val_u32;
        int32_t  val_s32;
        float    val_f32;
    };
};

#ifdef _MSC_VER
#   pragma pack(pop)
#else
#   error "proper packing not implemented!!!"
#endif

#define PARSECTX_RESERVE_OUTPUT(ctx, ptr, type, size)             \
    do                                                            \
    {                                                             \
        if ((ctx)->bjson_limit - (ctx)->bjson < (size)) return 0; \
        ptr = (type*)(ctx)->bjson;                                \
    }                                                             \
    while(0)
    
#define PARSECTX_ADVANCE_OUTPUT(ctx, size)                        \
    do { (ctx)->bjson += (size); } while(0) 

#define PARSECTX_ALLOCATE_OUTPUT(ctx, ptr, type, size)            \
    do                                                            \
    {                                                             \
        if ((ctx)->bjson_limit - (ctx)->bjson < (size)) return 0; \
        ptr = (type*)(ctx)->bjson;                                \
        (ctx)->bjson += size;                                     \
    }                                                             \
    while(0)

//TODO: what about 64 bit code????
#define PARSECTX_ALIGN_OUTPUT(ctx)                                \
    do { (ctx)->bjson = (uint8_t*)(((ptrdiff_t)(ctx)->bjson + 3) & (~3)); } while(0)

#define return_val_if_fail(cond, val) if (!(cond)) return (val)
#define return_if_fail(cond) if (!(cond)) return
#define INT64_T_FORMAT "lld"
#define MAX_UTF8_CHAR_LEN 6
#define TRUE  1
#define FALSE 0

typedef struct _mjson_parser_t  mjson_parser_t;
typedef struct _mjson_entry_t   mjson_entry_t;

static void mjson_next_token    (mjson_parser_t* context);

static int parse_value_list    (mjson_parser_t *context);
static int parse_key_value_pair(mjson_parser_t *context, int stop_token);

static mjson_element_t next_element(mjson_element_t element);

int mjson_parse(const char *json_data, size_t json_data_size, void* storage_buf, size_t storage_buf_size, const mjson_entry_t** top_element)
{
    uint32_t* fourcc;
    mjson_parser_t c = {
        TOK_NONE, 0,
        json_data, json_data + json_data_size,
        (uint8_t*)storage_buf, (uint8_t*)storage_buf + storage_buf_size
    };
    int stop_token = TOK_NONE;

    PARSECTX_ALLOCATE_OUTPUT(&c, fourcc, uint32_t, sizeof(uint32_t));
    *fourcc = '23JB';

    mjson_next_token(&c);
    
    *top_element = 0;
    
    if (c.token == TOK_LEFT_BRACKET)
    {
        mjson_next_token(&c);
        if (!parse_value_list(&c))
            return 0;
    }
    else
    {
        if (c.token == TOK_LEFT_CURVE_BRACKET)
        {
            stop_token = TOK_RIGHT_CURVE_BRACKET;
            mjson_next_token(&c);
        }

        if (!parse_key_value_pair(&c, stop_token))
            return 0;
    }

    if (c.token != TOK_NONE)
        return 0;

    *top_element = (mjson_entry_t*)(fourcc + 1);

    return 1;
}

mjson_element_t mjson_get_top_element(void* storage_buf, size_t storage_buf_size)
{
    mjson_element_t top = (mjson_element_t)storage_buf;
    
    return_val_if_fail(top, NULL);
    return_val_if_fail(top->id == MJSON_ID_DICT32 || top->id == MJSON_ID_ARRAY32, NULL);
    return_val_if_fail(top->val_u32 <= storage_buf_size, NULL);
    
    return top;
}

mjson_element_t mjson_get_element_first(mjson_element_t array)
{
    return_val_if_fail(array, NULL);
    return_val_if_fail(array->id == MJSON_ID_ARRAY32, NULL);
    
    return array + 1;
}

mjson_element_t mjson_get_element_next(mjson_element_t array, mjson_element_t current_value)
{
    mjson_element_t next = NULL;

    return_val_if_fail(array, NULL);
    return_val_if_fail(current_value, NULL);
    return_val_if_fail(array->id == MJSON_ID_ARRAY32, NULL);
    return_val_if_fail((uint8_t*)array + array->val_u32 > (uint8_t*)current_value, NULL);
    
    next = next_element(current_value);
    
    return_val_if_fail((uint8_t*)array + array->val_u32 > (uint8_t*)next, NULL);
    
    return next;
}

mjson_element_t mjson_get_element(mjson_element_t array, int index)
{
    mjson_element_t result;
    
    result = mjson_get_element_first(array);
    while (result && index--)
        result = mjson_get_element_next(array, result);
    
    return result;
}

mjson_element_t mjson_get_member_first(mjson_element_t dictionary, mjson_element_t* value)
{
    return_val_if_fail(dictionary, NULL);
    return_val_if_fail(dictionary->id == MJSON_ID_DICT32, NULL);
    return_val_if_fail((dictionary+1)->id == MJSON_ID_UTF8_KEY32, NULL);
    
    *value = next_element(dictionary+1);
    
    return dictionary + 1;
}

mjson_element_t mjson_get_member_next(mjson_element_t dictionary, mjson_element_t current_key, mjson_element_t* next_value)
{
    mjson_element_t next_key = NULL;

    return_val_if_fail(dictionary, NULL);
    return_val_if_fail(dictionary->id == MJSON_ID_DICT32, NULL);
    return_val_if_fail(current_key, NULL);
    return_val_if_fail((uint8_t*)dictionary + dictionary->val_u32 > (uint8_t*)current_key, NULL);
    return_val_if_fail(current_key->id == MJSON_ID_UTF8_KEY32, NULL);
    
    next_key = next_element(current_key);
    next_key = next_element(next_key);
    
    return_val_if_fail(next_key, NULL);
    return_val_if_fail((uint8_t*)dictionary + dictionary->val_u32 > (uint8_t*)next_key, NULL);
    return_val_if_fail(next_key->id == MJSON_ID_UTF8_KEY32, NULL);

    *next_value = next_element(next_key);
   
    return next_key;    
}

mjson_element_t mjson_get_member(mjson_element_t dictionary, const char* name)
{
    mjson_element_t key, result;
    
    key = mjson_get_member_first(dictionary, &result);
    while (key && strncmp(name, (char*)(key+1), key->val_u32) != 0)
        result = mjson_get_member_next(dictionary, key, &result);
    
    return result;
}

int mjson_get_type(mjson_element_t element)
{
    return_val_if_fail(element, MJSON_ID_NULL);
    
    return element->id;
}

const char* mjson_get_string(mjson_element_t element, const char* fallback)
{
    return_val_if_fail(element, fallback);
    return_val_if_fail(element->id == MJSON_ID_UTF8_STRING32, fallback);
    
    return (const char*)(element+1);
}

int32_t mjson_get_int(mjson_element_t element, int32_t fallback)
{
    return_val_if_fail(element, fallback);
    return_val_if_fail(element->id == MJSON_ID_SINT32, fallback);
    
    return element->val_s32;
}

float mjson_get_float(mjson_element_t element, float fallback)
{
    return_val_if_fail(element, fallback);
    return_val_if_fail(element->id == MJSON_ID_FLOAT32, fallback);
    
    return element->val_f32;
}

int mjson_get_bool(mjson_element_t element, int fallback)
{
    return_val_if_fail(element, fallback);
    return_val_if_fail(element->id == MJSON_ID_TRUE || element->id == MJSON_ID_FALSE, fallback);
    
    return element->id == MJSON_ID_TRUE;
}

int mjson_is_null(mjson_element_t element)
{
    return_val_if_fail(element, TRUE);

    return element->id == MJSON_ID_NULL;
}

/////////////////////////////////////////////////////////////////////////////
// API helpers
/////////////////////////////////////////////////////////////////////////////

static size_t element_size(mjson_element_t element)
{
    return_val_if_fail(element, 0);

    switch(element->id)
    {
        case MJSON_ID_NULL:
        case MJSON_ID_FALSE:
        case MJSON_ID_EMPTY_STRING:
        case MJSON_ID_TRUE:
            return sizeof(uint32_t);

        case MJSON_ID_UINT32:
        case MJSON_ID_SINT32:
        case MJSON_ID_FLOAT32:
            return sizeof(mjson_entry_t);

        case MJSON_ID_UTF8_KEY32:
        case MJSON_ID_UTF8_STRING32:
        case MJSON_ID_BINARY32:
        case MJSON_ID_ARRAY32:
        case MJSON_ID_DICT32:
            return sizeof(mjson_entry_t) + ((element->val_u32 + 3) & (~3));
    };

    return 0;
}

static mjson_element_t next_element(mjson_element_t element)
{
    size_t size;
    
    return_val_if_fail(element, 0);

    size = element_size(element);
    assert(size>0);
    
    return (mjson_element_t)((uint8_t*)element + size);
}

/////////////////////////////////////////////////////////////////////////////
// Lexer+Parser code
/////////////////////////////////////////////////////////////////////////////

static void unicode_cp_to_utf8(uint32_t uni_cp, char* utf8char/*[6]*/, size_t* charlen)
{
    uint32_t first, i;
    
    if (uni_cp < 0x80)
    {
        first   = 0;
        *charlen = 1;
    }
    else if (uni_cp < 0x800)
    {
        first   = 0xc0;
        *charlen = 2;
    }
    else if (uni_cp < 0x10000)
    {
        first   = 0xe0;
        *charlen = 3;
    }
    else if (uni_cp < 0x200000)
    {
        first   = 0xf0;
        *charlen = 4;
    }
    else if (uni_cp < 0x4000000)
    {
        first   = 0xf8;
        *charlen = 5;
    }
    else
    {
        first   = 0xfc;
        *charlen = 6;
    }

    for (i = *charlen - 1; i > 0; --i)
    {
        utf8char[i] = (uni_cp & 0x3f) | 0x80;
        uni_cp >>= 6;
    }
    utf8char[0] = uni_cp | first;
}



static void mjson_next_token(mjson_parser_t* context)
{
#define YYREADINPUT(c) (c>=e?0:*c)
#define YYCTYPE        char
#define YYCURSOR       c
#define YYMARKER       m

    const char* c = context->next;
    const char* e = context->end;
    const char* m = NULL;
    const char* s;
    int token = TOK_NONE;

    assert(context);
    return_if_fail(context->next != NULL);

    while (TRUE)
    {
        s = c;


        {
            YYCTYPE yych;
            unsigned int yyaccept = 0;

            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '<') {
                if (yych <= '"') {
                    if (yych <= '\f') {
                        if (yych <= 0x00) goto yy31;
                        if (yych <= 0x08) goto yy33;
                        if (yych >= '\v') goto yy33;
                    } else {
                        if (yych <= 0x1F) {
                            if (yych >= 0x0E) goto yy33;
                        } else {
                            if (yych <= ' ') goto yy2;
                            if (yych <= '!') goto yy33;
                            goto yy30;
                        }
                    }
                } else {
                    if (yych <= '.') {
                        if (yych <= '+') {
                            if (yych <= '*') goto yy33;
                            goto yy22;
                        } else {
                            if (yych <= ',') goto yy18;
                            if (yych <= '-') goto yy22;
                            goto yy24;
                        }
                    } else {
                        if (yych <= '0') {
                            if (yych <= '/') goto yy4;
                            goto yy20;
                        } else {
                            if (yych <= '9') goto yy23;
                            if (yych <= ':') goto yy14;
                            goto yy33;
                        }
                    }
                }
            } else {
                if (yych <= 'e') {
                    if (yych <= '\\') {
                        if (yych <= '@') {
                            if (yych <= '=') goto yy16;
                            goto yy33;
                        } else {
                            if (yych <= 'Z') goto yy29;
                            if (yych <= '[') goto yy10;
                            goto yy33;
                        }
                    } else {
                        if (yych <= '^') {
                            if (yych <= ']') goto yy12;
                            goto yy33;
                        } else {
                            if (yych == '`') goto yy33;
                            goto yy29;
                        }
                    }
                } else {
                    if (yych <= 't') {
                        if (yych <= 'm') {
                            if (yych <= 'f') goto yy27;
                            goto yy29;
                        } else {
                            if (yych <= 'n') goto yy28;
                            if (yych <= 's') goto yy29;
                            goto yy25;
                        }
                    } else {
                        if (yych <= '{') {
                            if (yych <= 'z') goto yy29;
                            goto yy6;
                        } else {
                            if (yych == '}') goto yy8;
                            goto yy33;
                        }
                    }
                }
            }
yy2:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            goto yy126;
yy3:
            {
                continue; 
            }
yy4:
            yyaccept = 0;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych == '*') goto yy108;
            if (yych == '/') goto yy110;
yy5:
            {
                context->token = TOK_INVALID;
                return;
            }
yy6:
            ++YYCURSOR;
            {
                token = TOK_LEFT_CURVE_BRACKET;
                goto done;
            }
yy8:
            ++YYCURSOR;
            {
                token = TOK_RIGHT_CURVE_BRACKET;
                goto done;
            }
yy10:
            ++YYCURSOR;
            {
                token = TOK_LEFT_BRACKET;
                goto done;
            }
yy12:
            ++YYCURSOR;
            {
                token = TOK_RIGHT_BRACKET;
                goto done;
            }
yy14:
            ++YYCURSOR;
            {
                token = TOK_COLON;
                goto done;
            }
yy16:
            ++YYCURSOR;
            {
                token = TOK_EQUAL;
                goto done;
            }
yy18:
            ++YYCURSOR;
            {
                token = TOK_COMMA;
                goto done;
            }
yy20:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'X') {
                if (yych <= '/') {
                    if (yych == '.') goto yy100;
                } else {
                    if (yych <= '9') goto yy100;
                    if (yych <= '@') goto yy21;
                    if (yych <= 'W') goto yy100;
                    goto yy104;
                }
            } else {
                if (yych <= '`') {
                    if (yych <= 'Z') goto yy100;
                    if (yych == '_') goto yy100;
                } else {
                    if (yych == 'x') goto yy104;
                    if (yych <= 'z') goto yy100;
                }
            }
yy21:
            {
                token = TOK_DEC_NUMBER;
                goto done;
            }
yy22:
            yyaccept = 0;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') {
                if (yych == '.') goto yy95;
                goto yy5;
            } else {
                if (yych <= '0') goto yy92;
                if (yych <= '9') goto yy93;
                goto yy5;
            }
yy23:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            goto yy71;
yy24:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy5;
            if (yych <= '9') goto yy63;
            goto yy5;
yy25:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych == 'r') goto yy59;
            goto yy49;
yy26:
            {
                token = TOK_IDENTIFIER;
                goto done;
            }
yy27:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych == 'a') goto yy54;
            goto yy49;
yy28:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych == 'u') goto yy50;
            goto yy49;
yy29:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            goto yy49;
yy30:
            yyaccept = 0;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 0x00) goto yy5;
            goto yy35;
yy31:
            ++YYCURSOR;
            { 
                context->token = TOK_NONE;
                return;
            }
yy33:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            goto yy5;
yy34:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy35:
            if (yych <= '"') {
                if (yych <= 0x00) goto yy36;
                if (yych <= '!') goto yy34;
                goto yy38;
            } else {
                if (yych == '\\') goto yy37;
                goto yy34;
            }
yy36:
            YYCURSOR = YYMARKER;
            if (yyaccept <= 2) {
                if (yyaccept <= 1) {
                    if (yyaccept == 0) {
                        goto yy5;
                    } else {
                        goto yy65;
                    }
                } else {
                    goto yy74;
                }
            } else {
                if (yyaccept == 3) {
                    goto yy21;
                } else {
                    goto yy120;
                }
            }
yy37:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'e') {
                if (yych <= '/') {
                    if (yych == '"') goto yy41;
                    if (yych <= '.') goto yy36;
                    goto yy41;
                } else {
                    if (yych <= '\\') {
                        if (yych <= '[') goto yy36;
                        goto yy41;
                    } else {
                        if (yych == 'b') goto yy41;
                        goto yy36;
                    }
                }
            } else {
                if (yych <= 'q') {
                    if (yych <= 'f') goto yy41;
                    if (yych == 'n') goto yy41;
                    goto yy36;
                } else {
                    if (yych <= 's') {
                        if (yych <= 'r') goto yy41;
                        goto yy36;
                    } else {
                        if (yych <= 't') goto yy41;
                        if (yych <= 'u') goto yy40;
                        goto yy36;
                    }
                }
            }
yy38:
            ++YYCURSOR;
            {
                token = TOK_NOESC_STRING;
                goto done;
            }
yy40:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy36;
                if (yych <= '9') goto yy45;
                goto yy36;
            } else {
                if (yych <= 'F') goto yy45;
                if (yych <= '`') goto yy36;
                if (yych <= 'f') goto yy45;
                goto yy36;
            }
yy41:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '"') {
                if (yych <= 0x00) goto yy36;
                if (yych <= '!') goto yy41;
            } else {
                if (yych == '\\') goto yy37;
                goto yy41;
            }
            ++YYCURSOR;
            {
                token = TOK_STRING;
                goto done;
            }
yy45:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy36;
                if (yych >= ':') goto yy36;
            } else {
                if (yych <= 'F') goto yy46;
                if (yych <= '`') goto yy36;
                if (yych >= 'g') goto yy36;
            }
yy46:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy36;
                if (yych >= ':') goto yy36;
            } else {
                if (yych <= 'F') goto yy47;
                if (yych <= '`') goto yy36;
                if (yych >= 'g') goto yy36;
            }
yy47:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy36;
                if (yych <= '9') goto yy41;
                goto yy36;
            } else {
                if (yych <= 'F') goto yy41;
                if (yych <= '`') goto yy36;
                if (yych <= 'f') goto yy41;
                goto yy36;
            }
yy48:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy49:
            if (yych <= 'Z') {
                if (yych <= '/') goto yy26;
                if (yych <= '9') goto yy48;
                if (yych <= '@') goto yy26;
                goto yy48;
            } else {
                if (yych <= '_') {
                    if (yych <= '^') goto yy26;
                    goto yy48;
                } else {
                    if (yych <= '`') goto yy26;
                    if (yych <= 'z') goto yy48;
                    goto yy26;
                }
            }
yy50:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych != 'l') goto yy49;
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych != 'l') goto yy49;
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'Z') {
                if (yych <= '/') goto yy53;
                if (yych <= '9') goto yy48;
                if (yych >= 'A') goto yy48;
            } else {
                if (yych <= '_') {
                    if (yych >= '_') goto yy48;
                } else {
                    if (yych <= '`') goto yy53;
                    if (yych <= 'z') goto yy48;
                }
            }
yy53:
            {
                token = TOK_NULL;
                goto done;
            }
yy54:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych != 'l') goto yy49;
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych != 's') goto yy49;
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych != 'e') goto yy49;
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'Z') {
                if (yych <= '/') goto yy58;
                if (yych <= '9') goto yy48;
                if (yych >= 'A') goto yy48;
            } else {
                if (yych <= '_') {
                    if (yych >= '_') goto yy48;
                } else {
                    if (yych <= '`') goto yy58;
                    if (yych <= 'z') goto yy48;
                }
            }
yy58:
            {
                token = TOK_FALSE;
                goto done;
            }
yy59:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych != 'u') goto yy49;
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych != 'e') goto yy49;
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'Z') {
                if (yych <= '/') goto yy62;
                if (yych <= '9') goto yy48;
                if (yych >= 'A') goto yy48;
            } else {
                if (yych <= '_') {
                    if (yych >= '_') goto yy48;
                } else {
                    if (yych <= '`') goto yy62;
                    if (yych <= 'z') goto yy48;
                }
            }
yy62:
            {
                token = TOK_TRUE;
                goto done;
            }
yy63:
            yyaccept = 1;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'D') {
                if (yych <= '/') goto yy65;
                if (yych <= '9') goto yy63;
            } else {
                if (yych <= 'E') goto yy66;
                if (yych == 'e') goto yy66;
            }
yy65:
            {
                token = TOK_FLOAT_NUMBER;
                goto done;
            }
yy66:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= ',') {
                if (yych != '+') goto yy36;
            } else {
                if (yych <= '-') goto yy67;
                if (yych <= '/') goto yy36;
                if (yych <= '9') goto yy68;
                goto yy36;
            }
yy67:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy36;
            if (yych >= ':') goto yy36;
yy68:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy65;
            if (yych <= '9') goto yy68;
            goto yy65;
yy70:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy71:
            if (yych <= 'E') {
                if (yych <= '/') {
                    if (yych == '.') goto yy76;
                    goto yy21;
                } else {
                    if (yych <= '9') goto yy70;
                    if (yych <= '@') goto yy21;
                    if (yych >= 'E') goto yy75;
                }
            } else {
                if (yych <= '`') {
                    if (yych <= 'Z') goto yy72;
                    if (yych != '_') goto yy21;
                } else {
                    if (yych == 'e') goto yy75;
                    if (yych >= '{') goto yy21;
                }
            }
yy72:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'Z') {
                if (yych <= '/') goto yy74;
                if (yych <= '9') goto yy72;
                if (yych >= 'A') goto yy72;
            } else {
                if (yych <= '_') {
                    if (yych >= '_') goto yy72;
                } else {
                    if (yych <= '`') goto yy74;
                    if (yych <= 'z') goto yy72;
                }
            }
yy74:
            {
                context->token = TOK_INVALID;
                return;
            }
yy75:
            yyaccept = 2;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '9') {
                if (yych <= ',') {
                    if (yych == '+') goto yy87;
                    goto yy74;
                } else {
                    if (yych <= '-') goto yy87;
                    if (yych <= '/') goto yy74;
                    goto yy88;
                }
            } else {
                if (yych <= '^') {
                    if (yych <= '@') goto yy74;
                    if (yych <= 'Z') goto yy72;
                    goto yy74;
                } else {
                    if (yych == '`') goto yy74;
                    if (yych <= 'z') goto yy72;
                    goto yy74;
                }
            }
yy76:
            yyaccept = 1;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych == 'E') goto yy79;
            if (yych == 'e') goto yy79;
            goto yy78;
yy77:
            yyaccept = 1;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy78:
            if (yych <= 'D') {
                if (yych <= '/') goto yy65;
                if (yych <= '9') goto yy77;
                goto yy65;
            } else {
                if (yych <= 'E') goto yy83;
                if (yych == 'e') goto yy83;
                goto yy65;
            }
yy79:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= ',') {
                if (yych != '+') goto yy36;
            } else {
                if (yych <= '-') goto yy80;
                if (yych <= '/') goto yy36;
                if (yych <= '9') goto yy81;
                goto yy36;
            }
yy80:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy36;
            if (yych >= ':') goto yy36;
yy81:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy65;
            if (yych <= '9') goto yy81;
            goto yy65;
yy83:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= ',') {
                if (yych != '+') goto yy36;
            } else {
                if (yych <= '-') goto yy84;
                if (yych <= '/') goto yy36;
                if (yych <= '9') goto yy85;
                goto yy36;
            }
yy84:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy36;
            if (yych >= ':') goto yy36;
yy85:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy65;
            if (yych <= '9') goto yy85;
            goto yy65;
yy87:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy36;
            if (yych <= '9') goto yy90;
            goto yy36;
yy88:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'Z') {
                if (yych <= '/') goto yy65;
                if (yych <= '9') goto yy88;
                if (yych <= '@') goto yy65;
                goto yy72;
            } else {
                if (yych <= '_') {
                    if (yych <= '^') goto yy65;
                    goto yy72;
                } else {
                    if (yych <= '`') goto yy65;
                    if (yych <= 'z') goto yy72;
                    goto yy65;
                }
            }
yy90:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy65;
            if (yych <= '9') goto yy90;
            goto yy65;
yy92:
            yyaccept = 3;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '9') {
                if (yych == '.') goto yy76;
                if (yych <= '/') goto yy21;
                goto yy97;
            } else {
                if (yych <= 'E') {
                    if (yych <= 'D') goto yy21;
                    goto yy96;
                } else {
                    if (yych == 'e') goto yy96;
                    goto yy21;
                }
            }
yy93:
            yyaccept = 3;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '9') {
                if (yych == '.') goto yy76;
                if (yych <= '/') goto yy21;
                goto yy93;
            } else {
                if (yych <= 'E') {
                    if (yych <= 'D') goto yy21;
                    goto yy96;
                } else {
                    if (yych == 'e') goto yy96;
                    goto yy21;
                }
            }
yy95:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy36;
            if (yych <= '9') goto yy63;
            goto yy36;
yy96:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= ',') {
                if (yych == '+') goto yy87;
                goto yy36;
            } else {
                if (yych <= '-') goto yy87;
                if (yych <= '/') goto yy36;
                if (yych <= '9') goto yy90;
                goto yy36;
            }
yy97:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '9') {
                if (yych == '.') goto yy76;
                if (yych <= '/') goto yy36;
                goto yy97;
            } else {
                if (yych <= 'E') {
                    if (yych <= 'D') goto yy36;
                    goto yy96;
                } else {
                    if (yych == 'e') goto yy96;
                    goto yy36;
                }
            }
yy99:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy100:
            if (yych <= 'E') {
                if (yych <= '7') {
                    if (yych == '.') goto yy76;
                    if (yych >= '0') goto yy99;
                } else {
                    if (yych <= '9') goto yy102;
                    if (yych <= '@') goto yy101;
                    if (yych <= 'D') goto yy72;
                    goto yy75;
                }
            } else {
                if (yych <= '`') {
                    if (yych <= 'Z') goto yy72;
                    if (yych == '_') goto yy72;
                } else {
                    if (yych == 'e') goto yy75;
                    if (yych <= 'z') goto yy72;
                }
            }
yy101:
            {
                token = TOK_OCT_NUMBER;
                goto done;
            }
yy102:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'E') {
                if (yych <= '/') {
                    if (yych == '.') goto yy76;
                    goto yy74;
                } else {
                    if (yych <= '9') goto yy102;
                    if (yych <= '@') goto yy74;
                    if (yych <= 'D') goto yy72;
                    goto yy75;
                }
            } else {
                if (yych <= '`') {
                    if (yych <= 'Z') goto yy72;
                    if (yych == '_') goto yy72;
                    goto yy74;
                } else {
                    if (yych == 'e') goto yy75;
                    if (yych <= 'z') goto yy72;
                    goto yy74;
                }
            }
yy104:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'Z') {
                if (yych <= '/') goto yy74;
                if (yych <= '9') goto yy106;
                if (yych <= '@') goto yy74;
                goto yy106;
            } else {
                if (yych <= '_') {
                    if (yych <= '^') goto yy74;
                    goto yy106;
                } else {
                    if (yych <= '`') goto yy74;
                    if (yych <= 'z') goto yy106;
                    goto yy74;
                }
            }
yy105:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy106:
            if (yych <= 'Z') {
                if (yych <= '9') {
                    if (yych >= '0') goto yy105;
                } else {
                    if (yych <= '@') goto yy107;
                    if (yych <= 'F') goto yy105;
                    goto yy72;
                }
            } else {
                if (yych <= '`') {
                    if (yych == '_') goto yy72;
                } else {
                    if (yych <= 'f') goto yy105;
                    if (yych <= 'z') goto yy72;
                }
            }
yy107:
            {
                token = TOK_HEX_NUMBER;
                goto done;
            }
yy108:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 0x00) goto yy36;
            if (yych == '*') goto yy114;
            goto yy108;
yy110:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 0x00) goto yy36;
            if (yych != '\n') goto yy110;
            ++YYCURSOR;
            {
                continue; 
            }
yy114:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych == '*') goto yy117;
            if (yych == '/') goto yy119;
            goto yy116;
yy115:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy116:
            if (yych <= 0x00) goto yy36;
            if (yych == '*') goto yy122;
            goto yy115;
yy117:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '*') {
                if (yych <= 0x00) goto yy36;
                if (yych <= ')') goto yy115;
                goto yy117;
            } else {
                if (yych == '/') goto yy121;
                goto yy115;
            }
yy119:
            ++YYCURSOR;
yy120:
            {
                continue; 
            }
yy121:
            yyaccept = 4;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 0x00) goto yy120;
            if (yych != '*') goto yy115;
yy122:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '*') {
                if (yych <= 0x00) goto yy36;
                if (yych <= ')') goto yy115;
            } else {
                if (yych == '/') goto yy119;
                goto yy115;
            }
yy123:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '*') {
                if (yych <= 0x00) goto yy36;
                if (yych <= ')') goto yy115;
                goto yy123;
            } else {
                if (yych == '/') goto yy121;
                goto yy115;
            }
yy125:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy126:
            if (yych <= '\f') {
                if (yych <= 0x08) goto yy3;
                if (yych <= '\n') goto yy125;
                goto yy3;
            } else {
                if (yych <= '\r') goto yy125;
                if (yych == ' ') goto yy125;
                goto yy3;
            }
        }

    }

done:
    context->token = token;
    context->start = s;
    context->next  = c;

#undef YYREADINPUT
#undef YYCTYPE           
#undef YYCURSOR          
#undef YYMARKER          
}

static int parse_number(mjson_parser_t *context)
{
    int              num_parsed;
    uint8_t          bjson_id;
    const char*      format;
    mjson_entry_t* bdata;

    switch(context->token)
    {
        case TOK_OCT_NUMBER:
            bjson_id = MJSON_ID_SINT32;
            format   = "%o";
            break;
        case TOK_HEX_NUMBER:
            bjson_id = MJSON_ID_SINT32;
            format   = "%x";
            break;
        case TOK_DEC_NUMBER:
            bjson_id = MJSON_ID_SINT32;
            format   = "%d";
            break;
        case TOK_FLOAT_NUMBER:
            bjson_id = MJSON_ID_FLOAT32;
            format   = "%f";
            break;
        default:
            assert(!"unknown token");
    }

    PARSECTX_ALLOCATE_OUTPUT(context, bdata, mjson_entry_t, (ptrdiff_t)sizeof(mjson_entry_t));
    bdata->id = bjson_id;

    num_parsed = sscanf(context->start, format, &bdata->val_u32);
    assert(num_parsed == 1);

    mjson_next_token(context);
    return 1;
}

static int parse_key(mjson_parser_t *context)
{
    mjson_entry_t* bdata;
    char*          str_dst;
    const char*    str_src;
    ptrdiff_t      str_len;
    
    assert(context->token==TOK_IDENTIFIER || context->token==TOK_NOESC_STRING);
    
    str_src = context->start;
    str_len = context->next - context->start;

    if (context->token==TOK_NOESC_STRING)
    {
        str_src += 1;
        str_len -= 2;
    }
    
    PARSECTX_ALLOCATE_OUTPUT(context, bdata, mjson_entry_t, (ptrdiff_t)sizeof(mjson_entry_t) + str_len + 1);
    bdata->id      = MJSON_ID_UTF8_KEY32;
    bdata->val_u32 = str_len;

    str_dst = (char*)(bdata + 1);
    
    memcpy(str_dst, str_src, str_len);
    str_dst[str_len] = 0;
    PARSECTX_ALIGN_OUTPUT(context);
    mjson_next_token(context);

    return 1;
}

static int parse_string(mjson_parser_t *context)
{
    mjson_entry_t* bdata;
    char*          str_dst;
    const char*    str_src;
    ptrdiff_t      str_len;

    str_len = context->next - context->start - 2;

    PARSECTX_ALLOCATE_OUTPUT(context, bdata, mjson_entry_t, (ptrdiff_t)sizeof(mjson_entry_t) + str_len + 1);
    bdata->id      = MJSON_ID_UTF8_STRING32;
    bdata->val_u32 = str_len;

    str_src = context->start + 1;
    str_dst = (char*)(bdata + 1);
    
    memcpy(str_dst, str_src, str_len);
    str_dst[str_len] = 0;
    PARSECTX_ALIGN_OUTPUT(context);
    mjson_next_token(context);

    return 1;
}

static int parse_escaped_string(mjson_parser_t *context)
{
#define YYREADINPUT(c) (c>=e?0:*c)
#define YYCTYPE        char
#define YYCURSOR       c
#define YYMARKER       m

    const char* c = context->start+1;
    const char* e = context->next;
    const char* m = NULL;
    const char* s;

    mjson_entry_t* bdata;
    char*            out;
    uint32_t         ch = 0;
    size_t           len;
    int              num_parsed;

    PARSECTX_ALLOCATE_OUTPUT(context, bdata, mjson_entry_t, (ptrdiff_t)sizeof(mjson_entry_t));
    bdata->id      = MJSON_ID_UTF8_STRING32;

    while (TRUE)
    {
        s = c;


        {
            YYCTYPE yych;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '"') {
                if (yych <= 0x00) goto yy135;
                if (yych >= '"') goto yy133;
            } else {
                if (yych == '\\') goto yy131;
            }
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            goto yy146;
yy130:
            {
                PARSECTX_ALLOCATE_OUTPUT(context, out, char, c - s);
                memcpy(out, s, c - s);

                continue;
            }
yy131:
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'e') {
                if (yych <= '/') {
                    if (yych == '"') goto yy138;
                    if (yych >= '/') goto yy138;
                } else {
                    if (yych <= '\\') {
                        if (yych >= '\\') goto yy138;
                    } else {
                        if (yych == 'b') goto yy138;
                    }
                }
            } else {
                if (yych <= 'q') {
                    if (yych <= 'f') goto yy138;
                    if (yych == 'n') goto yy138;
                } else {
                    if (yych <= 's') {
                        if (yych <= 'r') goto yy138;
                    } else {
                        if (yych <= 't') goto yy138;
                        if (yych <= 'u') goto yy136;
                    }
                }
            }
yy132:
            { 
                assert(!"reachable");
            }
yy133:
            ++YYCURSOR;
            {
                bdata->val_u32 = context->bjson - (uint8_t*)(bdata + 1);
                *context->bjson++ = 0;
                PARSECTX_ALIGN_OUTPUT(context);
                mjson_next_token(context);

                return 1;
            }
yy135:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            goto yy132;
yy136:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy137;
                if (yych <= '9') goto yy140;
            } else {
                if (yych <= 'F') goto yy140;
                if (yych <= '`') goto yy137;
                if (yych <= 'f') goto yy140;
            }
yy137:
            YYCURSOR = YYMARKER;
            goto yy132;
yy138:
            ++YYCURSOR;
            {
                char decoded = s[1];
                
                switch (s[1])
                {
                    case 'b':
                        decoded = '\b';
                        break;
                    case 'n':
                        decoded = '\n';
                        break;
                    case 'r':
                        decoded = '\r';
                        break;
                    case 't':
                        decoded = '\t';
                        break;
                    case 'f':
                        decoded = '\f';
                        break;
                }
                
                PARSECTX_ALLOCATE_OUTPUT(context, out, char, 1);
                *out = decoded;
                
                continue;
            }
yy140:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy137;
                if (yych >= ':') goto yy137;
            } else {
                if (yych <= 'F') goto yy141;
                if (yych <= '`') goto yy137;
                if (yych >= 'g') goto yy137;
            }
yy141:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy137;
                if (yych >= ':') goto yy137;
            } else {
                if (yych <= 'F') goto yy142;
                if (yych <= '`') goto yy137;
                if (yych >= 'g') goto yy137;
            }
yy142:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy137;
                if (yych >= ':') goto yy137;
            } else {
                if (yych <= 'F') goto yy143;
                if (yych <= '`') goto yy137;
                if (yych >= 'g') goto yy137;
            }
yy143:
            ++YYCURSOR;
            {
                PARSECTX_RESERVE_OUTPUT(context, out, char, 6);
                num_parsed = sscanf(s + 2, "%4x", &ch);
                assert(num_parsed == 1);
                unicode_cp_to_utf8(ch, out, &len);
                PARSECTX_ADVANCE_OUTPUT(context, len);

                continue;
            }
yy145:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy146:
            if (yych <= '"') {
                if (yych <= 0x00) goto yy130;
                if (yych <= '!') goto yy145;
                goto yy130;
            } else {
                if (yych == '\\') goto yy130;
                goto yy145;
            }
        }

    }

#undef YYREADINPUT
#undef YYCTYPE           
#undef YYCURSOR          
#undef YYMARKER 

    assert(!"reachable");
    return 0;
}

static int parse_value(mjson_parser_t *context)
{
    assert(context);
 
    switch (context->token)
    {
        case TOK_NULL:
            if (context->bjson_limit - context->bjson < sizeof(uint32_t)) return 0;
            *(uint32_t*)context->bjson = MJSON_ID_NULL;
            context->bjson += sizeof(uint32_t);
            mjson_next_token(context);
            break;
        case TOK_FALSE:
            if (context->bjson_limit - context->bjson < sizeof(uint32_t)) return 0;
            *(uint32_t*)context->bjson = MJSON_ID_FALSE;
            context->bjson += sizeof(uint32_t);
            mjson_next_token(context);
            break;
        case TOK_TRUE:
            if (context->bjson_limit - context->bjson < sizeof(uint32_t)) return 0;
            *(uint32_t*)context->bjson = MJSON_ID_TRUE;
            context->bjson += sizeof(uint32_t);
            mjson_next_token(context);
            break;
        case TOK_OCT_NUMBER:
        case TOK_HEX_NUMBER:
        case TOK_DEC_NUMBER:
        case TOK_FLOAT_NUMBER:
            if (!parse_number(context))
                return 0;
            break;
        case TOK_NOESC_STRING:
            if (!parse_string(context))
                return 0;
            break;
        case TOK_STRING:
            if (!parse_escaped_string(context))
                return 0;
            break;
        case TOK_LEFT_CURVE_BRACKET:
            mjson_next_token(context);
            if (!parse_key_value_pair(context, TOK_RIGHT_CURVE_BRACKET))
                return 0;
            break;
        case TOK_LEFT_BRACKET:
            mjson_next_token(context);
            if (!parse_value_list(context))
                return 0;
            break;
        default:
            return 0;
    }

    return 1;
}

static int parse_value_list(mjson_parser_t *context)
{
    mjson_entry_t* array;
    uint8_t*         data_start;
    int              expect_separator;

    assert(context);

    if (context->bjson_limit - context->bjson < sizeof(mjson_entry_t)) return 0;

    array     = (mjson_entry_t*)context->bjson;
    array->id = MJSON_ID_ARRAY32;

    context->bjson += sizeof(mjson_entry_t);
    data_start      = context->bjson;

    expect_separator = FALSE;

    while (context->token != TOK_RIGHT_BRACKET)
    {
        if (expect_separator && context->token == TOK_COMMA)
            mjson_next_token(context);
        else
            expect_separator = TRUE;

        if (!parse_value(context))
            return 0;
    }

    array->val_u32 = context->bjson - data_start;

    assert((array->val_u32 & 3) == 0);

    mjson_next_token(context);

    return 1;
}

static int parse_key_value_pair(mjson_parser_t* context, int stop_token)
{
    mjson_entry_t* dictionary;
    uint8_t*         data_start;
    int              expect_separator;
 
    assert(context);

    if (context->bjson_limit - context->bjson < sizeof(mjson_entry_t)) return 0;

    dictionary     = (mjson_entry_t*)context->bjson;
    dictionary->id = MJSON_ID_DICT32;

    context->bjson += sizeof(mjson_entry_t);
    data_start      = context->bjson;
    
    expect_separator = FALSE;
    while (context->token != stop_token)
    {
        if (expect_separator && context->token == TOK_COMMA)
            mjson_next_token(context);
        else
            expect_separator = TRUE;

        switch (context->token)
        {
            case TOK_IDENTIFIER:
            case TOK_NOESC_STRING:
                if (!parse_key(context))
                    return 0;
                break;        
            default:
                return 0;
        }

        if (context->token != TOK_COLON && context->token != TOK_EQUAL)
            return 0;

        mjson_next_token(context);

        if (!parse_value(context))
            return 0;
    }

    dictionary->val_u32 = context->bjson - data_start;
    
    assert((dictionary->val_u32 & 3) == 0);
    
    mjson_next_token(context);

    return 1;
}
